import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/modules/header/Header'
import SideBar from '@/modules/sideBar/SideBar'
import FeedSection from '@/modules/feedSection/FeedSection'
import {selectUser} from '@/app/redux/userSlice'
import {useSelector} from 'react-redux'
import Login from '@/modules/login/Login'
import News from '@/modules/news/News'

const inter = Inter({subsets: ['latin']})

export default function Home() {
  const user = useSelector(selectUser)
  return (
    <>
      <Head>
        <title>LinkedIn Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      {!user ? (
        <>
          <Login />
        </>
      ) : (
        <div className='app__body'>
          <SideBar />
          <FeedSection />
          <News />
        </div>
      )}
    </>
  )
}
